// frontend/src/components/SelectMonth.vue
<script setup lang="ts">
import { buildMonthlyReportURL } from '@/utils/build-monthly-report-url';
import { getEventDateValue } from '@/utils/get-event-date-value';
import { format } from 'date-fns/format';
import { useRouter } from 'vue-router';

const router = useRouter();
const handleChange = async (e: Event): Promise<void> => {
  e.preventDefault();
  const date = getEventDateValue(e);
  if (date === null) {
    return;
  }
  const nextURL = buildMonthlyReportURL(date);
  await router.push(nextURL);
};
const currentMonth = format(new Date(), 'yyyy-MM');
</script>

<template>
  <input type="month" :max="currentMonth" @change="handleChange" />
</template>

// src/components/SelectMonth/index.tsx
'use client';

import { buildMonthlyReportURL } from '@/build-monthly-report-url';
import { format } from 'date-fns/format';
import { ChangeEventHandler, FC } from 'react';

export const SelectMonth: FC = () => {
  const handleChange: ChangeEventHandler<HTMLInputElement> = (e) => {
    e.preventDefault();
    if (!e.target.valueAsDate) {
      return;
    }
    window.location.pathname = buildMonthlyReportURL(e.target.valueAsDate);
  };
  const currentMonth = format(new Date(), 'yyyy-MM');
  return <input type='month' max={currentMonth} onChange={handleChange} />;
};
